In [1]:
import numpy as np

In [5]:
a = np.random.randn(10)

In [6]:
a

array([-0.24953715, -0.54954617,  1.23990114, -0.8761219 ,  0.86729128,
       -0.36398598,  0.71844641, -0.73366194, -0.07824018, -1.70568204])

In [7]:
exp_a = np.exp(a)

In [8]:
exp_a

array([0.77916133, 0.57721171, 3.45527187, 0.4163946 , 2.38045412,
       0.69490094, 2.05124395, 0.4801475 , 0.92474229, 0.18164845])

In [9]:
result = exp_a / exp_a.sum()

In [10]:
result

array([0.06524996, 0.04833793, 0.28935774, 0.03487048, 0.19934837,
       0.05819367, 0.17177905, 0.0402094 , 0.07744147, 0.01521194])

In [11]:
result.sum()

np.float64(1.0)

In [12]:
A = np.random.randn(100, 5)

In [13]:
A

array([[ 8.64604344e-02, -2.88005742e-01,  1.74085994e+00,
        -5.67736714e-01, -1.47258021e+00],
       [-4.09942020e-01, -1.91509370e-03,  1.94518349e+00,
        -2.08550094e-01,  1.73910758e+00],
       [-1.31930401e+00,  9.51959441e-01,  4.98691949e-01,
        -1.62560591e-01,  3.45334906e-01],
       [-1.08556823e+00,  7.48459201e-01, -5.54347481e-01,
        -3.50088659e-01, -1.10120880e-01],
       [-9.93951336e-01, -7.64420051e-01,  7.54947437e-01,
         9.80030042e-01, -1.35204572e+00],
       [ 2.33786285e+00, -2.91677970e-01,  5.46225602e-02,
         1.42696652e+00, -7.34147087e-01],
       [ 1.24415892e-01,  2.89414545e-01, -6.62452352e-01,
        -8.93497353e-01,  8.06985786e-02],
       [ 1.86785972e+00,  6.89506176e-01, -4.44958142e-01,
        -4.02024278e-01,  1.34160723e+00],
       [ 1.36617690e+00,  1.84286285e-01, -1.05923837e+00,
        -5.19892541e-01, -1.05844430e+00],
       [-3.67797292e-01,  3.57338103e-02, -2.32875160e+00,
        -5.48215236e-01, -1.36934899e+00],
       [ 1.44634629e+00,  4.37205888e-01,  1.21179555e-01,
        -8.92928947e-02,  4.29907893e-01],
       [-1.24279358e+00,  1.06704966e-01, -3.21633699e-01,
         1.33896916e-01, -1.00541345e+00],
       [ 9.78938153e-01, -2.71893654e-01, -5.34434144e-01,
        -1.87124584e+00,  7.43728869e-01],
       [ 5.12563684e-01, -1.94231745e-02, -3.91960796e-01,
         3.75958545e-02,  1.44939568e+00],
       [ 7.56149849e-01, -1.05971672e+00,  3.90213040e-01,
         9.44842703e-01,  1.36881281e+00],
       [ 7.03532755e-01, -1.45860960e-01,  1.84343995e+00,
        -7.01982168e-01, -4.21458724e-01],
       [ 9.32459717e-01,  5.40636786e-02, -8.86718188e-01,
         1.74110613e+00, -1.32979767e+00],
       [ 1.26214646e+00, -1.09396186e+00,  3.36772748e-02,
         5.36792160e-01,  1.16708433e+00],
       [ 7.54328671e-01, -2.15412965e+00, -2.10282366e-01,
         5.15438685e-01, -1.59591008e+00],
       [ 2.22215339e+00, -3.57589238e-01,  9.48858584e-01,
         1.41628854e-01,  2.93333977e-01],
       [ 4.97078883e-01, -5.66241103e-02,  5.83873279e-01,
        -1.40493318e+00,  4.38254455e-02],
       [-5.53459656e-01,  9.57098411e-01, -1.11380977e+00,
        -2.99363150e-01,  5.29517722e-01],
       [-3.03482897e+00,  4.33529440e-01, -1.79735774e-01,
        -5.40749304e-01, -1.17619652e+00],
       [-4.69901366e-01, -1.07525517e+00, -3.57590995e-01,
         4.19080288e-01, -1.57580665e+00],
       [ 1.54549885e+00, -5.00955754e-01, -2.28444187e-01,
         2.65147302e+00,  9.70767573e-01],
       [ 8.72256774e-01,  1.04759969e+00, -7.57539483e-01,
        -1.21895440e+00,  7.37352598e-01],
       [-5.16043272e-01,  7.52743644e-01, -4.64394491e-01,
        -1.23608557e+00,  1.70114456e-01],
       [-2.72088935e-01, -1.01655989e+00, -1.05805895e+00,
         9.90685744e-02, -4.38056327e-01],
       [ 4.36080575e-01, -3.54609165e-01,  9.28847600e-01,
         7.13811993e-02, -6.42024302e-01],
       [-8.23065457e-01, -2.85025731e-01,  1.37603007e-01,
        -3.61265650e-01, -6.67179351e-01],
       [-5.65665122e-01,  4.34905950e-01,  5.08393804e-01,
        -2.31573911e-01, -7.33051483e-01],
       [ 1.19885454e+00, -1.50412449e+00, -4.82490230e-01,
         1.87455228e+00, -6.84376641e-01],
       [ 1.63016546e+00, -2.83478872e-01, -3.90561764e-01,
         6.13866114e-01,  6.87286754e-01],
       [ 3.52500598e-02,  4.55945806e-01, -2.92217210e-01,
         5.26227046e-01,  4.02051371e-01],
       [-6.62674664e-01,  8.17820968e-02,  1.36192325e-02,
        -5.58466734e-01, -7.74479733e-01],
       [-2.99043025e+00, -7.99564280e-01,  1.59304326e+00,
        -8.01170534e-01,  9.44133007e-01],
       [ 4.50314805e-01,  4.87142280e-02, -1.60120023e+00,
        -3.86291411e-01, -1.07150774e+00],
       [-4.93142027e-01, -2.96249352e-01,  1.21439868e+00,
        -8.92507487e-01, -3.99160056e-01],
       [ 3.39121847e-02, -2.62308645e-01,  1.10529568e+00,
         1.36377498e+00, -1.61936983e+00],
       [ 6.46800603e-02, -6.66976064e-01,  1.01574481e+00,
        -3.64695107e-01, -1.44944148e-01],
       [ 1.51503211e+00,  1.26391472e+00,  6.84442994e-01,
        -7.06636110e-01,  5.13538281e-02],
       [-4.21799663e-01,  5.31403680e-02, -4.94714288e-01,
         7.01093123e-01, -1.48820063e+00],
       [-3.17364012e+00, -6.60752883e-01, -2.09508691e-01,
         4.41510146e-01,  8.44727895e-01],
       [-1.27750931e+00, -1.68956807e+00,  1.00725825e+00,
        -1.26010110e+00, -8.59014263e-01],
       [ 2.39416183e+00,  4.75649384e-01, -1.32064109e-01,
         2.86454762e-01,  5.11021306e-01],
       [ 3.19800369e-01, -1.45061089e-01,  5.36259759e-01,
        -1.37083744e+00, -9.37723805e-02],
       [ 1.12281371e+00,  1.39620468e+00, -1.73139955e+00,
        -3.93982579e-01, -4.37441347e-01],
       [ 1.61578543e-01, -2.71701639e-01,  1.03657968e+00,
         4.58906250e-01, -1.36505660e-01],
       [ 1.17619926e+00, -9.22217247e-01, -7.02080633e-01,
        -1.41540065e+00, -9.51311424e-01],
       [-1.15657308e+00, -5.52516544e-01, -2.37887791e-01,
        -5.97098456e-01,  9.10044531e-01],
       [-1.41472834e+00, -1.44416635e-01,  4.20858033e-01,
        -6.34483809e-01,  7.30948521e-01],
       [-1.71472810e+00,  4.95536072e-01,  4.23580961e-01,
         1.76329560e+00, -1.29606962e-01],
       [ 2.39705598e+00,  1.01520040e+00, -1.29520648e+00,
         8.60244091e-01,  7.31710640e-01],
       [-1.16046283e+00,  6.98043817e-01,  8.63469475e-01,
         7.21609056e-01,  4.26189803e-02],
       [ 2.13252618e-01,  1.79206428e+00,  1.50580779e-01,
        -1.95303401e+00,  3.44928865e-01],
       [-4.89503881e-01, -2.58445425e-02, -1.99840357e+00,
         4.40527254e-01,  1.07778703e+00],
       [-3.31926600e-01, -6.20695817e-03,  1.00984213e+00,
         1.40902742e+00, -9.26664817e-01],
       [-6.83806356e-01,  1.34767473e+00,  5.55086794e-01,
        -3.15687125e-01, -1.12306674e+00],
       [-2.34342263e-01, -6.10410098e-01, -7.19236908e-02,
        -1.00656009e+00,  3.54573328e-01],
       [ 2.16711975e+00, -2.36258605e-01, -4.30364783e-01,
        -2.66824559e+00, -5.03901609e-01],
       [-8.01773374e-01, -1.28804500e+00, -1.04395862e+00,
        -6.95336241e-01, -1.59617620e+00],
       [-1.56191695e-01, -3.89606385e-01,  9.86245224e-01,
         1.49228633e-01,  1.61924012e+00],
       [ 1.73572851e+00,  4.26149276e-01, -1.50962627e+00,
         2.82514430e-01,  1.57530815e+00],
       [-1.42225170e-01,  1.08453468e+00,  3.58709562e-01,
         3.43960949e-01,  8.51271325e-01],
       [-5.31635845e-01,  8.44438521e-01,  1.72799048e+00,
        -1.84752107e+00,  1.06678926e+00],
       [ 7.71996339e-01,  1.47421566e+00,  1.16886456e+00,
        -1.12077479e+00, -2.54360433e-01],
       [-3.43598447e-01, -1.32904962e-01, -1.00248857e+00,
         1.04766174e+00, -1.13667410e+00],
       [-6.63453736e-01,  6.76161029e-01,  3.31533645e-01,
        -2.52110520e-01, -1.45560979e+00],
       [-1.45078278e+00, -1.56681516e+00, -3.27755053e-01,
        -1.01980829e+00, -1.17671638e+00],
       [-2.37161618e+00,  1.60775897e-01,  1.41148596e+00,
         2.47988659e+00,  1.25795116e+00],
       [ 7.16741177e-01,  9.27572611e-01,  2.14946960e-01,
        -4.44587472e-01,  7.87444128e-01],
       [-2.80270462e-03, -1.28953735e+00,  6.33757347e-01,
         1.42533273e+00,  6.08086126e-01],
       [-1.39111894e+00, -8.64221875e-01, -2.62181233e-01,
         4.82638782e-01, -9.38157367e-01],
       [ 6.11279837e-03, -1.15198598e+00,  4.30781712e-01,
        -5.62048664e-01,  2.31776490e-01],
       [-1.27329362e+00, -5.88238858e-01, -1.30128376e+00,
         1.47776984e-01,  9.97274333e-01],
       [-3.35478645e-01,  8.47144933e-02, -1.30469565e+00,
        -2.50301047e-01, -6.43283232e-01],
       [ 5.36151517e-01,  1.26485495e+00, -4.27001501e-01,
        -3.77558259e-01, -1.88087319e-01],
       [-1.04810581e+00, -4.35946968e-01, -1.79942287e-01,
        -2.97604359e-01,  1.35364725e+00],
       [-1.16596975e+00,  3.75990275e-01, -7.75219209e-01,
        -3.60277295e-01,  4.17847729e-01],
       [-8.04723479e-01,  2.45211280e-02,  2.30149240e+00,
        -6.10623506e-01, -2.07597974e-01],
       [-3.09398795e-02,  3.13181399e-01,  3.89900470e-01,
        -2.36084515e-01,  4.34632755e-01],
       [-1.61668857e-03,  7.39473246e-01,  1.40461128e+00,
        -4.57906652e-01, -1.09121073e+00],
       [ 8.96955294e-01, -1.22647937e+00,  1.06997053e-01,
        -7.44286095e-01, -3.67098552e-01],
       [ 9.39405954e-01,  1.48150092e+00,  5.04140824e-01,
         1.73955023e+00, -2.71907825e-02],
       [-5.96725285e-02, -8.75671707e-01,  1.21924985e+00,
         6.04339201e-01,  1.65176623e+00],
       [ 2.11825649e+00, -1.21840080e+00, -2.34453604e+00,
        -1.60676930e+00, -1.47178134e+00],
       [-2.25374157e-02,  3.58880958e-02, -3.22051247e-01,
        -3.82153682e-01, -2.27993731e-01],
       [-9.06540736e-01, -7.48652920e-02, -1.41132284e-02,
        -9.12364869e-01,  3.98654779e-01],
       [ 6.10792283e-01, -5.34466365e-02, -1.71615418e+00,
         1.54484102e+00, -4.12104680e-01],
       [-9.51172369e-01,  1.24638384e-01, -5.95199669e-01,
         1.57865277e-01, -7.17242084e-01],
       [ 4.13528802e-01,  1.62016260e+00,  5.67702646e-01,
        -4.44009694e-01,  2.12443259e+00],
       [-4.08698803e-01, -5.80893521e-02, -8.05307128e-01,
        -2.88196953e-01, -9.45294675e-02],
       [ 4.99598853e-01,  1.27171212e+00, -6.72524216e-01,
         4.71627475e-01,  1.76102148e+00],
       [ 1.11026603e+00,  6.54628498e-01, -1.06011058e+00,
         1.35868319e+00,  1.11832070e+00],
       [-4.02951096e-01, -4.22035552e-01,  3.33328300e-01,
         1.79358498e-01, -5.34315741e-01],
       [ 2.53271418e-01, -4.36163397e-01,  7.35120316e-02,
        -1.10247495e+00, -2.07629380e+00],
       [ 3.30712397e-01,  1.27313909e+00,  1.82900840e+00,
        -1.84966149e+00,  8.28648934e-01],
       [-3.62002931e-02,  4.70325290e-01,  1.46744361e+00,
        -1.21082109e-01, -1.17810463e-01],
       [ 4.64266058e-01, -7.19507531e-01,  3.75970643e-01,
        -8.76476080e-01, -3.43259644e-02],
       [-1.78522972e-01,  9.10599495e-01,  9.89108714e-01,
         8.71386738e-01, -9.50364005e-01]])

In [14]:
exp_A = np.exp(A) / np.exp(A).sum(axis=1, keepdims=True)

In [15]:
exp_A

array([[0.1307567 , 0.08991566, 0.68384948, 0.06797508, 0.02750307],
       [0.04377688, 0.06583376, 0.46138434, 0.05354368, 0.37546133],
       [0.0395031 , 0.38284977, 0.24331945, 0.12560256, 0.20872511],
       [0.07299863, 0.45690162, 0.12417122, 0.15231035, 0.19361817],
       [0.06287501, 0.07909741, 0.3614225 , 0.45265499, 0.04395008],
       [0.61631139, 0.04444318, 0.06283499, 0.247858  , 0.02855244],
       [0.25295754, 0.29833598, 0.11516356, 0.09140575, 0.24213716],
       [0.4759851 , 0.14650111, 0.04711393, 0.04918076, 0.2812191 ],
       [0.61150181, 0.18754659, 0.05408207, 0.09274451, 0.05412503],
       [0.26041286, 0.38986456, 0.03664636, 0.21742422, 0.095652  ],
       [0.4530031 , 0.16513422, 0.12038949, 0.09753973, 0.16393346],
       [0.07938155, 0.30605491, 0.19942253, 0.31449132, 0.10064969],
       [0.42468761, 0.12157387, 0.09350188, 0.02456125, 0.33567539],
       [0.19357485, 0.11371297, 0.07834638, 0.12038518, 0.49398061],
       [0.203697  , 0.03314086, 0.14127337, 0.24599875, 0.37589001],
       [0.19515819, 0.08346411, 0.61015783, 0.04786074, 0.06335913],
       [0.25467389, 0.10580395, 0.04129766, 0.57170908, 0.02651542],
       [0.35958312, 0.03408431, 0.10526449, 0.17409325, 0.32697484],
       [0.43130607, 0.02353196, 0.1643843 , 0.33965419, 0.04112348],
       [0.61504938, 0.04661675, 0.17215715, 0.07679795, 0.08937877],
       [0.28982863, 0.16659852, 0.31610809, 0.04326213, 0.18420263],
       [0.09668353, 0.43790463, 0.05520718, 0.12465371, 0.28555095],
       [0.01449577, 0.46508282, 0.25187937, 0.17555226, 0.09298978],
       [0.18421961, 0.10056204, 0.20611597, 0.44814205, 0.06096033],
       [0.20475532, 0.02645278, 0.03473934, 0.61880479, 0.11524778],
       [0.29542435, 0.35204384, 0.05789416, 0.03649596, 0.25814169],
       [0.1237265 , 0.4400377 , 0.13028473, 0.06022161, 0.24572947],
       [0.23656611, 0.11236548, 0.10779785, 0.3428816 , 0.20038897],
       [0.2424233 , 0.10994669, 0.39680794, 0.16834004, 0.08248203],
       [0.12373619, 0.21191633, 0.32337747, 0.19636037, 0.14460963],
       [0.11249081, 0.30595641, 0.32928726, 0.15711261, 0.09515291],
       [0.29668037, 0.01987925, 0.05521919, 0.58309674, 0.04512445],
       [0.49223801, 0.07262564, 0.06525059, 0.17815661, 0.19172914],
       [0.15820806, 0.24095416, 0.11402796, 0.258498  , 0.22831181],
       [0.14132432, 0.29752972, 0.27792499, 0.15684614, 0.12637483],
       [0.00595717, 0.05327466, 0.5829307 , 0.05318915, 0.30464832],
       [0.40828328, 0.27324277, 0.05248074, 0.1768594 , 0.08913381],
       [0.1052379 , 0.12813908, 0.58042712, 0.07058785, 0.11560804],
       [0.11580797, 0.08611749, 0.33809161, 0.43781489, 0.02216803],
       [0.1807867 , 0.08697857, 0.46795991, 0.1176769 , 0.14659793],
       [0.39161395, 0.30464865, 0.17066241, 0.04246195, 0.09061305],
       [0.14376954, 0.2311696 , 0.1336597 , 0.44190918, 0.04949198],
       [0.00796904, 0.09834205, 0.15442304, 0.29610517, 0.4431607 ],
       [0.07131182, 0.04722877, 0.70052469, 0.0725641 , 0.10837063],
       [0.666483  , 0.09785651, 0.05329213, 0.08098853, 0.10137983],
       [0.26913698, 0.16907781, 0.33418003, 0.04962936, 0.17797582],
       [0.35695019, 0.46918034, 0.02056073, 0.07831976, 0.07498898],
       [0.16297921, 0.10567226, 0.39096723, 0.2194118 , 0.1209695 ],
       [0.68048649, 0.083462  , 0.10401427, 0.05096851, 0.08106873],
       [0.06674081, 0.12210401, 0.16725205, 0.11677994, 0.52712319],
       [0.04638089, 0.16520701, 0.29075296, 0.10120338, 0.39645576],
       [0.0178959 , 0.16317705, 0.1518481 , 0.57974906, 0.08732989],
       [0.59516061, 0.14945207, 0.01482876, 0.12799861, 0.11255995],
       [0.04019351, 0.25780724, 0.30418553, 0.26395468, 0.13385904],
       [0.12431962, 0.60284943, 0.1167674 , 0.01424733, 0.14181623],
       [0.09862646, 0.15680436, 0.02181156, 0.24997746, 0.47278016],
       [0.08022257, 0.11111043, 0.30691586, 0.45749179, 0.04425935],
       [0.07058812, 0.53826066, 0.24365542, 0.10200084, 0.04549496],
       [0.19504854, 0.1339117 , 0.22944585, 0.09010995, 0.35148395],
       [0.80515431, 0.07279561, 0.05995231, 0.00639597, 0.05570181],
       [0.25227142, 0.15512542, 0.19801055, 0.28060352, 0.11398909],
       [0.08205972, 0.06497695, 0.25720776, 0.11137107, 0.48438452],
       [0.41762519, 0.11273108, 0.01626848, 0.09764811, 0.35572715],
       [0.09627244, 0.32830463, 0.15887485, 0.15654887, 0.25999921],
       [0.05062699, 0.20044885, 0.48498165, 0.01358002, 0.25036249],
       [0.19942762, 0.40249018, 0.29658077, 0.03004452, 0.07145691],
       [0.13842128, 0.17088576, 0.07162267, 0.55644144, 0.06262885],
       [0.10544104, 0.40252882, 0.28518535, 0.15909399, 0.0477508 ],
       [0.12789927, 0.11388745, 0.39318127, 0.19680581, 0.16822619],
       [0.00448099, 0.05638691, 0.19694946, 0.57326481, 0.16891782],
       [0.23660351, 0.29213535, 0.14325003, 0.07407345, 0.25393765],
       [0.10894288, 0.03008688, 0.20589858, 0.45439148, 0.20068018],
       [0.07208908, 0.12209503, 0.2229261 , 0.46949627, 0.11339351],
       [0.21445941, 0.067358  , 0.32792646, 0.12150544, 0.26875069],
       [0.05623433, 0.1115622 , 0.05468215, 0.23289742, 0.54462389],
       [0.21161312, 0.32212924, 0.08028178, 0.23042774, 0.15554812],
       [0.23042502, 0.47753094, 0.08795035, 0.0924082 , 0.11168548],
       [0.05438471, 0.10030765, 0.12957329, 0.11519019, 0.60054416],
       [0.07010852, 0.32766911, 0.10362668, 0.15692009, 0.3416756 ],
       [0.03489299, 0.07996032, 0.77938234, 0.04236768, 0.06339667],
       [0.15769273, 0.22246498, 0.24020405, 0.12844538, 0.25119287],
       [0.12271838, 0.2574903 , 0.50075657, 0.07775806, 0.0412767 ],
       [0.48786921, 0.05835895, 0.22142615, 0.09451948, 0.13782621],
       [0.16742185, 0.28789955, 0.10833752, 0.37265794, 0.06368315],
       [0.07990759, 0.03533492, 0.28708929, 0.15522608, 0.44244212],
       [0.91008746, 0.03235872, 0.01049342, 0.02194446, 0.02511594],
       [0.23182685, 0.24577494, 0.17182507, 0.16180218, 0.18877096],
       [0.09596178, 0.22043998, 0.23424733, 0.09540451, 0.35394641],
       [0.2214054 , 0.11394963, 0.02160768, 0.56343058, 0.07960671],
       [0.10357399, 0.30371718, 0.14785897, 0.31397829, 0.13087157],
       [0.0872062 , 0.29146188, 0.10174292, 0.0369933 , 0.48259569],
       [0.17890001, 0.25402597, 0.12032769, 0.20181046, 0.24493587],
       [0.12536197, 0.27132534, 0.0388257 , 0.12190401, 0.44258298],
       [0.2476314 , 0.15700911, 0.02826332, 0.31746213, 0.24963405],
       [0.14844913, 0.14564292, 0.30998432, 0.26574891, 0.13017473],
       [0.37141256, 0.18639697, 0.3103045 , 0.09573339, 0.03615258],
       [0.10205558, 0.26189516, 0.45660268, 0.01153221, 0.16791437],
       [0.11113807, 0.18443533, 0.49990455, 0.10209375, 0.10242831],
       [0.3235567 , 0.09904762, 0.29621305, 0.08465907, 0.19652356],
       [0.09518741, 0.28286512, 0.30596766, 0.27198786, 0.04399195]])

In [16]:
exp_A.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
exp_A.sum(axis=1, keepdims=True).shape

(100, 1)

In [18]:
exp_A.sum(axis=0, keepdims=True)

array([[21.63074307, 19.09262902, 21.53603821, 19.07078369, 18.66980602]])

#### Matrix Addition - Practice

In [19]:
import pandas as pd

W = pd.DataFrame([[23,129,10,85],
              [678,2,99,88],
              [111,89,67,23]])
W

     0    1   2   3
0   23  129  10  85
1  678    2  99  88
2  111   89  67  23

In [159]:
W.shape

(3, 4)

In [160]:
X = pd.DataFrame([[1,2,3,4,],[7,8,9,10],[12,13,14,15]])
X

    0   1   2   3
0   1   2   3   4
1   7   8   9  10
2  12  13  14  15

In [161]:
X.shape

(3, 4)

In [170]:
b = np.array([25,50,39])
b

array([25, 50, 39])

In [171]:
W_T = W.T
W_T.shape

(4, 3)

In [172]:
W_T.dot(X)

      0     1     2     3
0  6101  6913  7725  8537
1  1211  1431  1651  1871
2  1507  1683  1859  2035
3   977  1173  1369  1565

In [173]:
W_T

     0    1    2
0   23  678  111
1  129    2   89
2   10   99   67
3   85   88   23

In [181]:
X.dot(W.T) + b

      0      1     2
0   676   1381   621
1  2158   6583  2361
2  3393  10918  3811